### ISSUE TITLE
text-decoration-thickness property change on hover stops working at certain font sizes

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/reported-bugs#60]
**Upstream bug:** https://bugs.webkit.org/show_bug.cgi?id=224483
**Date:** 2021-04-13
**Reported by:** Vanita Barrett
**Related to:** https://github.com/alphagov/govuk-frontend/issues/2188

---

### Overview

1. Open https://codepen.io/36degrees/pen/LYxQBbm or the attached example.html
2. Hover over both links of the links on the line “17px link / with colour change” - text decoration thickness property expands to 3px
3. Hover over both of the links on the line “19px link / with colour change” - text decoration thickness property only expands to 3px on the link with colour change.

### Expected result

The text underline thickness should increase to 3px on all links when hovered.

### Actual result

In this example, the text-decoration-thickness only increases to 3px on hover on links up to a font-size of 19px, unless the link also has a colour change on hover.

The font-size at which the text-decoration-thickness property stops working changes depending on the thickness being set on hover. In the CodePen / attached example, text-decoration-thickness is set to 3px on hover and stops working at links of font-size: 19px. Other examples:

text-decoration-thickness on hover: 2px 
font-size value at which it stops working: 15px

text-decoration-thickness on hover: 5px 
font-size value at which it stops working: 27px

**Comment by 36degrees** [comment]
A fix for this has landed in Webkit (https://github.com/WebKit/WebKit/pull/8372) 🎉

**Comment by 36degrees** [comment]
Fix included in [Safari Tech Preview 163](https://webkit.org/blog/13839/release-notes-for-safari-technology-preview-163/)

**Comment by 36degrees** [comment]
The fix was then [included in Safari 16.4](https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes#:~:text=Fixed%20text%2Ddecoration%2Dthickness%20property%20not%20repainting%20when%20changed.)

It doesn't appear to be an issue in Safari 12.1 (the first version of Safari to support `text-decoration-thickness`), but it does affect 13.1.

Unfortunately I'm not able to test 13.0 so unsure exactly when the bug was introduced, but let's assume this affected 13.0 through 16.3 inclusive.
